services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    volumes:
      # Mount source code for development (comment out for production)
      - ./:/var/www/app
      # Don't overwrite vendor directory with local files
      - /var/www/app/vendor
    environment:
      # Development environment
      PHP_IDE_CONFIG: "serverName=xkphp2"
    # Ensures container keeps running
    tty: true
    restart: unless-stopped
    depends_on:
      - mockserver
    networks:
      - app-network

  mockserver:
    build:
      context: https://github.com/erlangxk/mockAPI.git#main
    networks:
      - app-network

networks:
  app-network:
    driver: bridge